<form role="form" method="post">
    <div class="row">
        <div class="col-xs-2">
            <div class="form-group">
                <label for="asin" class="control-label">
                    <?php echo __('Amazon ASIN Number'); ?>
                </label>
                <input value="<?php echo getKbPostVar('asin');?>" type="text" name="asin" class="form-control" placeholder="ASIN">
                <input value="1" type="hidden" name="2kbDownloadImagesASIN">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary" name="submit"><?php echo __('Download'); ?></button>
            </div>
        </div>
    </div>
</form>
